fedora_path: "http://localhost"
default_dsid: "MODS"
username: "my_fedora_username"
password: "my_fedora_password"
gsearch_username: "my_gsearch_username"
gsearch_password: "my_gesarch_password"
port: "8080"
destination_directory: "output"
